spring:
  data:
    mongodb:
      uri: mongodb+srv://valladahugo:admin@webfluxcluster.ku9a3mc.mongodb.net/webflux-course?retryWrites=true&w=majority
      auto-index-creation: true
  application:
    name: webflux-course